#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Proc-NiceSleep
version:      0.76
version_from: NiceSleep.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
