--- #YAML:1.0
name:                Proc-NiceSleep
version:             0.86
abstract:            yield system in an intelligent fashion
license:             ~
author:              
    - Josh Rabinowitz <Josh Rabinowitz>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
